site_title: "MeDoW"
app_debug: true
logger:
  name: "MeDoW"
  format: "%(asctime)s # %(levelname)s [%(name)s] > %(message)s"
  level: 10 # see https://docs.python.org/3/library/logging.html#logging-levels (10=debug, 20=info, 30=warn, 40=err, 50=crit)
server:
  host: 0.0.0.0
  port: 5000
  debug: true
persistence:
  sqlite_datafile: "sql/medow.sqlite3"
repository_limits:
  select_min: 1
  select_max: 1000
  select_fallback: 10
listing_limits:
  images: 125
  scraps: 1000
worker_thread:
  max_workers: 1
scrappers:
  storage_path: "static/scrap/"
  storage_path_for_static: "scrap/"
  roumen_kecy:
    base_url: "https://www.rouming.cz"
    img_base: "https://www.rouming.cz/upload"
    href_needle: "roumingShow.php"
    url_params: {}
  roumen_maso:
    base_url: "https://www.roumenovomaso.cz"
    img_base: "https://www.roumenovomaso.cz/upload"
    href_needle: "masoShow.php"
    url_params:
      agree: "on"
